name: Trie
on:
  push:
    branches: [master, develop]
    tags: ['*']
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

env:
  cwd: ${{github.workspace}}/packages/trie

defaults:
  run:
    working-directory: packages/trie

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-trie:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci --omit=peer
        working-directory: ${{github.workspace}}

      - run: npm run lint
      - run: npm run coverage
      - uses: codecov/codecov-action@v3
        with:
          files: ${{ env.cwd }}/coverage/lcov.info
          flags: trie

  # trie-benchmarks:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 18
  #         cache: 'npm'

  #     - run: npm ci
  #       working-directory: ${{github.workspace}}

  #     - run: npm run benchmarks | tee output.txt
  #       working-directory: ${{ env.cwd }}

  #     # Run git stash in case github-action-benchmark has trouble switching to gh-pages branch due to differing package-locks
  #     - run: git stash

  #     - name: Compare benchmarks
  #       uses: rhysd/github-action-benchmark@v1
  #       with:
  #         tool: 'benchmarkjs'
  #         # Where the output from the benchmark tool is stored
  #         output-file-path: ${{ env.cwd }}/output.txt
  #         # Location of data in gh-pages branch
  #         benchmark-data-dir-path: dev/bench/trie
  #         # GitHub API token to make a commit comment
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         # Push and deploy to GitHub pages branch automatically (if on master)
  #         auto-push: ${{ github.ref == 'refs/heads/master' }}
  #         # Only keep and display the last 30 commits worth of benchmark data
  #         max-items-in-chart: 30

  #     # Re-apply git stash to prepare for saving back to cache.
  #     # Avoids exit code 1 by checking if there are changes to be stashed first
  #     - run: STASH_LIST=`git stash list` && [ ! -z $STASH_LIST ] && git stash apply || echo "No files to stash-apply. Skipping…"
